name: Code Intelligence Check

on:
  push:
    branches: [ master ]

jobs:
  create_check:
    runs-on: ubuntu-latest
    steps:
      - uses: WichanTestCI/simple-findings-check-action@v1
        with:
          who-to-greet: 'CI team members'
          ci_fuzz_api_token: ${{ secrets.CI_FUZZ_API_TOKEN }}
          token: ${{ secrets.GITHUB_TOKEN }}
          repo: '${{ github.event.repository.name }}'
