name: Code Intelligence Check

on:
  push:
    branches: [ master ]

jobs:
  create_check:
    runs-on: ubuntu-latest
    steps:
      - uses: WichanTestCI/simple-findings-check-action@main
        with:
          name: 'Our first check!'
          who-to-greet: 'CI team members'
          ci-fuzz-api-token: ${{ secrets.CI_FUZZ_API_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repo: ${{ github.event.repository.owner.login }}/${{ github.event.repository.name }}
