name: Code Intelligence Check

on:
  push:
    branches: [ master ]

jobs:
  create_check:
    runs-on: ubuntu-latest
    steps:
      - uses: octocat/hello-world-javascript-action@v1.1
        with:
          who-to-greet: 'CI team members'
