name: Code Intelligence Check

on:
  pull_request:
    branches: [ master ]

env:
  FUZZING_SERVER_ADDRESS: demo.code-intelligence.com:6773
  WEB_APP_ADDRESS:  https://demo.code-intelligence.com


jobs:
  create_check:
    runs-on: ubuntu-latest
    steps:
      - uses: WichanTestCI/simple-findings-check-action@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          who-to-greet: CI team members
