name: Code Intelligence Check

on:
  push:
    branches: [ master ]

jobs:
  create_check:
    runs-on: ubuntu-latest
    steps:
      - uses: WichanTestCI/simple-findings-check-action@v1
        with:
          who-to-greet: 'CI team members'
