name: Code Intelligence Check

on:
  push:
    branches: [ master ]

jobs:
  create_check:
    runs-on: ubuntu-latest
    steps:
      - uses: CC-CIFUZZ-TEST/simple-findings-check-action@main
        with:
          name: 'CI Fuzz Findings'
          ci-fuzz-api-token: ${{ secrets.CI_FUZZ_API_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repo: ${{ github.event.repository.owner.login }}/${{ github.event.repository.name }}
